# Generated by Django 3.0.3 on 2020-03-24 19:15

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
from django.db import migrations, models

import home.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TwoColumnGeneralPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('heading', home.models.Heading(classname='full title')),
                                                          ('paragraph', wagtail.core.blocks.RichTextBlock()),
                                                          ('image', wagtail.images.blocks.ImageChooserBlock()),
                                                          ('document', wagtail.documents.blocks.DocumentChooserBlock()),
                                                          ('two_columns', wagtail.core.blocks.StructBlock([(
                                                                                                           'left_column',
                                                                                                           wagtail.core.blocks.StreamBlock(
                                                                                                               [(
                                                                                                                'heading',
                                                                                                                home.models.Heading(
                                                                                                                    classname='full title')),
                                                                                                                (
                                                                                                                'paragraph',
                                                                                                                wagtail.core.blocks.RichTextBlock()),
                                                                                                                (
                                                                                                                'image',
                                                                                                                wagtail.images.blocks.ImageChooserBlock()),
                                                                                                                (
                                                                                                                'document',
                                                                                                                wagtail.documents.blocks.DocumentChooserBlock()),
                                                                                                                (
                                                                                                                'button',
                                                                                                                wagtail.core.blocks.StructBlock(
                                                                                                                    [(
                                                                                                                     'text',
                                                                                                                     wagtail.core.blocks.CharBlock(
                                                                                                                         max_length=100)),
                                                                                                                     (
                                                                                                                     'url',
                                                                                                                     wagtail.core.blocks.URLBlock()),
                                                                                                                     (
                                                                                                                     'color',
                                                                                                                     wagtail.core.blocks.ChoiceBlock(
                                                                                                                         choices=[
                                                                                                                             (
                                                                                                                             'dark-tan',
                                                                                                                             'Dark Tan'),
                                                                                                                             (
                                                                                                                             'green',
                                                                                                                             'Green'),
                                                                                                                             (
                                                                                                                             'orange',
                                                                                                                             'Orange'),
                                                                                                                             (
                                                                                                                             'red',
                                                                                                                             'Red'),
                                                                                                                             (
                                                                                                                             'tan',
                                                                                                                             'Tan')])),
                                                                                                                     (
                                                                                                                     'alignment',
                                                                                                                     wagtail.core.blocks.ChoiceBlock(
                                                                                                                         choices=[
                                                                                                                             (
                                                                                                                             'center',
                                                                                                                             'Center'),
                                                                                                                             (
                                                                                                                             'justify',
                                                                                                                             'Justified'),
                                                                                                                             (
                                                                                                                             'left',
                                                                                                                             'Left'),
                                                                                                                             (
                                                                                                                             'right',
                                                                                                                             'Right')]))]))],
                                                                                                               icon='arrow-left',
                                                                                                               label='Left column content')),
                                                                                                           (
                                                                                                           'right_column',
                                                                                                           wagtail.core.blocks.StreamBlock(
                                                                                                               [(
                                                                                                                'heading',
                                                                                                                home.models.Heading(
                                                                                                                    classname='full title')),
                                                                                                                (
                                                                                                                'paragraph',
                                                                                                                wagtail.core.blocks.RichTextBlock()),
                                                                                                                (
                                                                                                                'image',
                                                                                                                wagtail.images.blocks.ImageChooserBlock()),
                                                                                                                (
                                                                                                                'document',
                                                                                                                wagtail.documents.blocks.DocumentChooserBlock()),
                                                                                                                (
                                                                                                                'button',
                                                                                                                wagtail.core.blocks.StructBlock(
                                                                                                                    [(
                                                                                                                     'text',
                                                                                                                     wagtail.core.blocks.CharBlock(
                                                                                                                         max_length=100)),
                                                                                                                     (
                                                                                                                     'url',
                                                                                                                     wagtail.core.blocks.URLBlock()),
                                                                                                                     (
                                                                                                                     'color',
                                                                                                                     wagtail.core.blocks.ChoiceBlock(
                                                                                                                         choices=[
                                                                                                                             (
                                                                                                                             'dark-tan',
                                                                                                                             'Dark Tan'),
                                                                                                                             (
                                                                                                                             'green',
                                                                                                                             'Green'),
                                                                                                                             (
                                                                                                                             'orange',
                                                                                                                             'Orange'),
                                                                                                                             (
                                                                                                                             'red',
                                                                                                                             'Red'),
                                                                                                                             (
                                                                                                                             'tan',
                                                                                                                             'Tan')])),
                                                                                                                     (
                                                                                                                     'alignment',
                                                                                                                     wagtail.core.blocks.ChoiceBlock(
                                                                                                                         choices=[
                                                                                                                             (
                                                                                                                             'center',
                                                                                                                             'Center'),
                                                                                                                             (
                                                                                                                             'justify',
                                                                                                                             'Justified'),
                                                                                                                             (
                                                                                                                             'left',
                                                                                                                             'Left'),
                                                                                                                             (
                                                                                                                             'right',
                                                                                                                             'Right')]))]))],
                                                                                                               icon='arrow-right',
                                                                                                               label='Right column content'))])),
                                                          ('embedded_video',
                                                           wagtail.embeds.blocks.EmbedBlock(icon='media')),
                                                          ('html', wagtail.core.blocks.RawHTMLBlock()), (
                                                          'dropdown_image_list', wagtail.core.blocks.StructBlock([(
                                                                                                                  'list_items',
                                                                                                                  wagtail.core.blocks.ListBlock(
                                                                                                                      wagtail.core.blocks.StructBlock(
                                                                                                                          [
                                                                                                                              (
                                                                                                                              'image',
                                                                                                                              wagtail.images.blocks.ImageChooserBlock(
                                                                                                                                  label='Image')),
                                                                                                                              (
                                                                                                                              'title',
                                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                                  label='Title',
                                                                                                                                  max_length=200)),
                                                                                                                              (
                                                                                                                              'text',
                                                                                                                              wagtail.core.blocks.RichTextBlock(
                                                                                                                                  label='Text'))]),
                                                                                                                      label='List Item'))]))],
                                                         blank=True, null=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('heading', home.models.Heading(classname='full title')), (
                'paragraph', wagtail.core.blocks.RichTextBlock(classname='paragraph', required=True)), ('tan_bg_text',
                                                                                                        wagtail.core.blocks.RichTextBlock(
                                                                                                            classname='paragraph',
                                                                                                            help_text='Paragraph with a tan background',
                                                                                                            required=False)),
                                                          ('image', wagtail.images.blocks.ImageChooserBlock()),
                                                          ('html', wagtail.core.blocks.RawHTMLBlock()), (
                                                          'dropdown_image_list', wagtail.core.blocks.StructBlock([(
                                                                                                                  'list_items',
                                                                                                                  wagtail.core.blocks.ListBlock(
                                                                                                                      wagtail.core.blocks.StructBlock(
                                                                                                                          [
                                                                                                                              (
                                                                                                                              'image',
                                                                                                                              wagtail.images.blocks.ImageChooserBlock(
                                                                                                                                  label='Image')),
                                                                                                                              (
                                                                                                                              'title',
                                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                                  label='Title',
                                                                                                                                  max_length=200)),
                                                                                                                              (
                                                                                                                              'text',
                                                                                                                              wagtail.core.blocks.RichTextBlock(
                                                                                                                                  label='Text'))]),
                                                                                                                      label='List Item'))]))])),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
