# Generated by Django 3.0.3 on 2020-03-24 22:00

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.db import migrations

import home.models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpage',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='twocolumngeneralpage',
            name='banner',
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', home.models.Heading(classname='full title')), (
            'paragraph', wagtail.core.blocks.RichTextBlock(classname='paragraph', required=True)),
                                                   ('image', wagtail.images.blocks.ImageChooserBlock()),
                                                   ('html', wagtail.core.blocks.RawHTMLBlock())]),
        ),
        migrations.AlterField(
            model_name='twocolumngeneralpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', home.models.Heading(classname='full title')),
                                                   ('paragraph', wagtail.core.blocks.RichTextBlock()),
                                                   ('image', wagtail.images.blocks.ImageChooserBlock()),
                                                   ('document', wagtail.documents.blocks.DocumentChooserBlock()),
                                                   ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True,
                                                  null=True),
        ),
    ]
