# Generated by Django 3.0.3 on 2020-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20200324_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='summary',
            field=models.CharField(default='', help_text='Brief summary of the post', max_length=500),
            preserve_default=False,
        ),
    ]
