# Generated by Django 3.0.3 on 2020-03-25 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blog', '0005_blogtagindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
