# Generated by Django 3.0.3 on 2020-03-25 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_delete_blogtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='parent',
            field=models.ForeignKey(blank=True,
                                    help_text='Unlike tags, categories can have a hierarchy so they can be more specifically organized.',
                                    null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children',
                                    to='blog.BlogCategory'),
        ),
    ]
