# Generated by Django 3.0.3 on 2020-05-12 19:56

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_auto_20200402_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', home.models.Heading()), (
            'paragraph', wagtail.core.blocks.RichTextBlock(classname='paragraph', required=True)),
                                                   ('image', wagtail.images.blocks.ImageChooserBlock()),
                                                   ('html', wagtail.core.blocks.RawHTMLBlock(required=False)), ('code',
                                                                                                                wagtail.core.blocks.StructBlock(
                                                                                                                    [(
                                                                                                                     'code',
                                                                                                                     wagtail.core.blocks.TextBlock(
                                                                                                                         max_length=20000)),
                                                                                                                     (
                                                                                                                     'language',
                                                                                                                     wagtail.core.blocks.ChoiceBlock(
                                                                                                                         choices=[
                                                                                                                             (
                                                                                                                             'python',
                                                                                                                             'Python'),
                                                                                                                             (
                                                                                                                             'django',
                                                                                                                             'Django'),
                                                                                                                             (
                                                                                                                             'bash',
                                                                                                                             'Bash'),
                                                                                                                             (
                                                                                                                             'css',
                                                                                                                             'CSS'),
                                                                                                                             (
                                                                                                                             'dockerfile',
                                                                                                                             'Dockerfile'),
                                                                                                                             (
                                                                                                                             'javascript',
                                                                                                                             'Javascript'),
                                                                                                                             (
                                                                                                                             'ini',
                                                                                                                             'Ini'),
                                                                                                                             (
                                                                                                                             'sql',
                                                                                                                             'SQL'),
                                                                                                                             (
                                                                                                                             'json',
                                                                                                                             'JSON'),
                                                                                                                             (
                                                                                                                             'markdown',
                                                                                                                             'Markdown'),
                                                                                                                             (
                                                                                                                             'html',
                                                                                                                             'HTML'),
                                                                                                                             (
                                                                                                                             'nginx',
                                                                                                                             'Nginx')],
                                                                                                                         required=False))])),
                                                   ('table', wagtail.contrib.table_block.blocks.TableBlock())]),
        ),
    ]
